name: Python Application CI with MySQL and Packer

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build-packer-image:
    name: Build Packer Custom Image
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=mysql+pymysql://test_user:test_password@127.0.0.1:3306/test_db" >> $GITHUB_ENV
          echo "SECRET_KEY=mysecretkey" >> $GITHUB_ENV

      - name: Run pytest
        run: |
          pytest test_app.py --disable-warnings

      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Create the .env file inside the GITHUB_WORKSPACE directory
      - name: Create .env file
        run: |
          mkdir -p ${GITHUB_WORKSPACE}/api
          echo "DATABASE_URL=\"${{ secrets.DATABASE_URL }}\"" > ${GITHUB_WORKSPACE}/api/.env
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run Packer init
        run: |
          cd aws-packer
          packer init .

      - name: Build Packer image
        run: |
          cd aws-packer
          packer build -var "envfile=${GITHUB_WORKSPACE}/api/.env" .
